# NODEJS IMAGE WITH YARN
FROM node:14.15.5-alpine3.12
WORKDIR /usr/app
COPY package.json .
# CHECK VERSION FOR NPM
RUN npm --version
# CHECK VERSION FOR YARN
RUN yarn --version
RUN yarn
COPY . .
CMD [ "yarn","run", "dev" ]
# EXPOSE GRAPHQL PORT TO RUN QUERIES IN PLAYGROUND
EXPOSE 3000
# EXPOSE FE APP TO USER
EXPOSE 8080
