const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADDED_ITEM: "ADDED_ITEM",
  REMOVED_ITEM: "REMOVED_ITEM",
  INCREMENTED_ITEM_QUANTITY: "INCREMENTED_ITEM_QUANTITY",
  DECREMENTED_ITEM_QUANTITY: "DECREMENTED_ITEM_QUANTITY",
  CLEAR_CART: "CLEAR_CART"
};

export default CartActionTypes;
