/*
 * TBH, just used the code-editor to select all these...
 */
const nestedBrandNames = [
  ['Pansy Espinoza', 'Finley Barron', 'Chavez Pope'],
  ['Simone Gallagher', 'Christian Short', 'Elisa Ellis'],
  ['Goldie Lynch', 'Miller Bird', 'Melanie Conner'],
  ['Mullins Estrada', 'Merritt Frye', 'Hattie Nash'],
  ['Gena Garrison', 'Kline Robles', 'Liz Edwards'],
  ['Lynne Parrish', 'Moss Hampton', 'Alston Santana'],
  ['Dominguez Lee', 'Naomi Casey', 'Alma Robertson'],
  ['Estrada Newman', 'Mallory Humphrey', 'Deann Carlson'],
  ['Richardson Anthony', 'Roman Foreman', 'Anne Reeves'],
  ['Imogene Rodriguez', 'Brandi Dunlap', 'Bolton Haley'],
  ['Holloway Harmon', 'Jillian David', 'Oneill Tillman'],
  ['Stokes Talley', 'Coleman Mckenzie', 'Phelps Bean'],
  ['Mandy Sandoval', 'Watson Sweeney', 'Bethany Payne'],
  ['Francisca Knight', 'Meyers Harrison', 'Leola Compton'],
  ['Barlow Morin', 'Katy Yates', 'Maria Beasley'],
  ['Elvia Mccarty', 'Ingram Powell', 'Barry Coleman'],
  ['Sharpe Grant', 'Donovan Trujillo', 'Odonnell Whitney'],
  ['Blake Mcmillan', 'Brewer Walters', 'Leonor Roberts'],
  ['Caroline Butler', 'Ofelia Sweet', 'Collins Freeman'],
  ['Cameron Petersen', 'Houston Schmidt', 'Carolyn Stanton'],
  ['Genevieve Nichols', 'Clara Robinson', 'Wiggins Levine'],
  ['Hess Sharp', 'Doyle Slater', 'Mays Snider'],
  ['Laurel Lancaster', 'Page Thornton', 'Owen Reilly'],
  ['Morin Ellison', 'Erma Campbell', 'Sosa Head'],
  ['Marlene Goodwin', 'Connie Nolan', 'Christie Weaver'],
  ['Lane Barr', 'Daniel Ayers', 'Pratt Riddle'],
  ['Rodgers Morton', 'Leonard Hahn', 'Conley Schroeder'],
  ['Sonja Baird', 'Lucile Dean', 'Mcgee Hale'],
  ['William Collins', 'Juarez Moss', 'Ramona Leon'],
  ['Kinney Cunningham', 'Gould Hansen', 'Cash Mcneil'],
  ['Mollie Hunt', 'Effie Hicks', 'Florence Aguilar'],
  ['Bessie Nelson', 'Schmidt Nguyen', 'Jaime Mason'],
  ['Benton Velazquez', 'Garrett Knowles', 'Perez Hull'],
  ['Cohen Byrd', 'Mckee Brewer', 'Emily Coffey'],
  ['Conner Mcknight', 'Mcdonald James', 'Holder Keith'],
  ['Emma Collier', 'Gray Mendez', 'Dickerson Crane'],
  ['Harper Crosby', 'Wood Gray', 'Lowery Workman'],
  ['Rhoda Hensley', 'John Vaughn', 'Burke Clayton'],
  ['Dolly Case', 'Margie Rush', 'Christi Carr'],
  ['Bartlett Cain', 'Hood Noble', 'Justine Evans'],
  ['Murray Wiley', 'Eula Wise', 'Meyer Bruce'],
  ['Felecia Howell', 'Buchanan Hobbs', 'Beulah Wagner'],
  ['Maricela Booth', 'Mayo Morales', 'Tamika Cohen'],
  ['Roach Gay', 'Jodi Smith', 'Murphy Larsen'],
  ['Muriel Frank', 'Debra Baxter', 'Reid Howard'],
  ['Christina Mccall', 'Hendrix Mcguire', 'Montoya Chavez'],
  ['Simpson Goff', 'Ingrid Day', 'Gertrude Buckner'],
  ['Morrison Bender', 'Ana Oneil', 'Callahan Schultz'],
  ['Nellie Parker', 'Alyssa Roach', 'Nieves Green'],
  ['Osborn Norris', 'Ortiz Underwood', 'Chang Daniels'],
  ['Deana Gilmore', 'Kelly Michael', 'Colette Logan'],
  ['Jeanne Hodges', 'Kitty Kramer', 'Evans Rich'],
  ['Thompson Mcdowell', 'Jenna Rojas', 'Matthews Waters'],
  ['Sears Frost', 'Nunez Burris', 'Johnson Serrano'],
  ['Chrystal Barber', 'Stevens Odonnell', 'Marci Key'],
  ['Nell Mcclain', 'Roberts Flores', 'Booth Stanley'],
  ['Cole Jacobs', 'Santiago Todd', 'Logan Rosario'],
  ['Johnnie Wooten', 'Ayers Fulton', 'Castaneda Vazquez'],
  ['Aurora Bonner', 'Parrish Mccormick', 'Rodriquez Shields'],
  ['Ryan Mclaughlin', 'Holcomb Ramirez', 'Lela Houston'],
  ['Vasquez Joyce', 'Chan Leonard', 'James Gaines'],
  ['Johanna Klein', 'Mcclure Gonzalez', 'Solomon Gordon'],
  ['Rosanna Herring', 'Cara Randall', 'Alfreda Carey'],
  ['Higgins Winters', 'Concepcion Frazier', 'Fry Higgins'],
  ['Miriam Morse', 'Shirley Reyes', 'Emerson Miles'],
  ['Audrey Chen', 'Byers Walker', 'Virgie Greene'],
  ['Sullivan Hood', 'Fanny Harrington', 'Burgess Meyer'],
  ['Poole Jimenez', 'Lorrie Middleton', 'Robles Yang'],
  ['Judy Rowe', 'Chapman Hoffman', 'Nina Rosales'],
  ['Franco Craft', 'Hopper Weeks', 'Mcknight Spears'],
  ['Angie Holmes', 'Dionne Melton', 'Heather Torres'],
  ['Amy Meyers', 'Gillespie Kline', 'Herminia Phelps'],
  ['Leanne Gentry', 'Dawson Estes', 'Park Poole'],
  ['Elaine Petty', 'Stone Golden', 'Kelley Oconnor'],
  ['Hillary Velez', 'Humphrey Christensen', 'Figueroa George'],
  ['Robbie Montgomery', 'Concetta Tanner', 'Valencia Richard'],
  ['Rojas Nixon', 'Estella Reynolds', 'Carroll Olsen'],
  ['Iris Mann', 'Vazquez Hebert', 'Teresa Hudson'],
  ['Marsh Chase', 'Mathis Cabrera', 'Aisha Cherry'],
  ['Castro Lester', 'Duran Figueroa', 'Gutierrez Fuller'],
  ['Langley Cash', 'Paulette Vega', 'Terry Daniel'],
  ['Mckay Webster', 'Iva Knapp', 'Tommie Murphy'],
  ['Bryan Randolph', 'Marianne Diaz', 'Morse Lawson'],
  ['Pace Combs', 'Joann Graham', 'Rosalinda Flynn'],
  ['Fields Vaughan', 'Bishop Gilbert', 'Hill Rose'],
  ['Eunice Decker', 'Maritza Spencer', 'David Valdez'],
  ['Rowena Cooke', 'Nielsen Price', 'Pacheco Wright'],
  ['Madelyn Larson', 'Adrienne Roth', 'Hobbs Good'],
  ['Shana Thompson', 'Hooper Vance', 'Pearlie Lang'],
  ['Charlene Pacheco', 'Workman Rasmussen', 'Shannon Morrison'],
  ['Osborne Joseph', 'Brown Lowe', 'Frances Brady'],
  ['Elsa Alston', 'Odom Savage', 'Rose Terrell'],
  ['Deirdre Clemons', 'Leona Henderson', 'Black Love'],
  ['Sawyer Guy', 'Bettye Battle', 'Jamie Simmons'],
];

exports.seed = async function seedAllMockBrands(knex) {
  // ❗️This will delete existing brands
  await knex('merchant_products').del();
  await knex('brands').del();

  const brandNames = nestedBrandNames.flatMap(brands => brands);

  await knex('brands').insert(
    brandNames.map(name => {
      return { name: name };
    })
  );
};
