version: '2.4'
services:

  mongo:
    container_name: mongo-bonsai
    image: mongo:4.4
    command: mongod --config /etc/mongo/mongod.conf
    ports:
      - "27019:27017"
    volumes:
      - ./mongo/mongo_db_init.js:/docker-entrypoint-initdb.d/mongo_db_init.js
      - ./mongo/health-check.sh:/usr/local/bin/health-check.sh
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
    healthcheck:
      test: ["CMD", "/usr/local/bin/health-check.sh"]
      interval: 5s
      timeout: 5s
      retries: 30
