//CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
//USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_LIKED_PRODUCT = 'SET_USER_LIKED_PRODUCT';
